var RU_TO_LAT_FULL = {
  "а": "a",
  "б": "b",
  "в": "v",
  "г": "g",
  "д": "d",
  "е": "e",
  "ё": "yo",
  "ж": "zh",
  "з": "z",
  "и": "i",
  "й": "j",
  "к": "k",
  "л": "l",
  "м": "m",
  "н": "n",
  "о": "o",
  "п": "p",
  "р": "r",
  "с": "s",
  "т": "t",
  "у": "u",
  "ф": "f",
  "х": "h",
  "ц": "c",
  "ч": "ch",
  "ш": "sh",
  "щ": "sz",
  "ъ": "#",
  "ы": "y",
  "ь": "'",
  "э": "eh",
  "ю": "ju",
  "я": "ja",
}

var RU_TO_LAT_HARD_ONLY = {
  "б": "b",
  "в": "v",
  "г": "g",
  "д": "d",
  "ё": "yo",
  "ж": "zh",
  "з": "z",
  "и": "i",
  "й": "j",
  "л": "l",
  "н": "n",
  "п": "p",
  "р": "r",
  "с": "s",
  "т": "t",
  "у": "u",
  "ф": "f",
  "х": "h",
  "ц": "c",
  "ч": "ch",
  "ш": "sh",
  "щ": "sz",
  "ъ": "#",
  "ы": "y",
  "ь": "'",
  "э": "eh",
  "ю": "ju",
  "я": "ja",
}

ALL_LETTERS_FULL = Array.from(Object.keys(RU_TO_LAT_FULL));
ALL_LETTERS_HARD_ONLY = Array.from(Object.keys(RU_TO_LAT_HARD_ONLY));

module.exports = { RU_TO_LAT_FULL, RU_TO_LAT_HARD_ONLY, ALL_LETTERS_FULL, ALL_LETTERS_HARD_ONLY };
